
if vim.g.vscode then
  require "tony.options"
  require "tony.vscode"
  require "tony.colorscheme"
  require "tony.rainbow"
else
  require "tony.options"
  require "tony.keymaps"
  require "tony.plugins"
  require "tony.colorscheme"
  require "tony.cmp"
  require "tony.lsp"
  require "tony.telescope"
  require "tony.treesitter"
  require "tony.autopairs"
  require "tony.comment"
  require "tony.gitsigns"
  require "tony.nvim-tree"
  require "tony.bufferline"
  require "tony.lualine"
  require "tony.indentline"
  require "tony.alpha"
  require "tony.which-key"
  require "tony.autocommands"
  require "tony.presence"
  require "tony.illuminate"
  require "tony.rainbow"
  require "tony.project"
  require "tony.colorizer"
  require "tony.competitive"
end
